### PR TITLE
chore/binder: add test on binder

### PR DESCRIPTION
**Pull request by caicancai**
2023-11-15 18-38-36屏幕截图

### CODE REVIEW

**Comment by caicancai** [comment]
I'll see if I can fill in the other tests tomorrow

**Comment by caicancai** [comment]
2023-11-16 09-44-04屏幕截图

**Comment by caicancai** [comment]
@wangrunji0408 hi, excuse me. if you have time, could you review my two pr? I can close this pr if there is a problem

**Comment by skyzh** [comment]
will take a look this weekend :)

**Review by skyzh — COMMENTED** [review]
I don't think these new tests are actually testing + comparing with some expected result? In this case, it looks better to make this test part of sqlplannertest, so that we can find regressions across commits.

**Comment by caicancai** [comment]
> I don't think these new tests are actually testing + comparing with some expected result? In this case, it looks better to make this test part of sqlplannertest, so that we can find regressions across commits.

thank your review and advice

**Pull request closed without merging**
