### PR TITLE
fix: add row_handler to schema

### LINKED ISSUE #450: optimizer: table scan schema should include row handler
Currently, the implementation of TableScan's schema is not correct.

https://github.com/risinglightdb/risinglight/blob/c221b085ceb4a61fe1cf1e6c9d6caa36b7215a2e/src/optimizer/plan_nodes/logical_table_scan.rs#L75-L77

When `with_row_handler` is enabled, we should have an extra i64 column for row handlers at the end.

### PR DESCRIPTION
**Pull request by yinfredyue**
This PR close #450.

Signed-off-by: Yue Yin <yueyin.dev@gmail.com>

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
Indeed this is not always correct -- row handler will only be in TableScan when there's update / delete. We can fix this when we decide on a rewrite of binder / planner / optimizer.

**Comment by yinfredyue** [comment]
> Indeed this is not always correct -- row handler will only be in TableScan when there's update / delete. We can fix this when we decide on a rewrite of binder / planner / optimizer.

You are right. I did not fully understand how the row handlers are created/used when I was creating this PR. 

> row handler will only be in TableScan when there's update / delete. 

I just read the planner & executor code and this is indeed the case. However, what's the reason for creating this extra temporary "row identifier" for create/delete? Why cannot we use, say, `row_id` or `pk`?

**Comment by skyzh** [comment]
We don't have pk. Row handler is like a row id, but row handler contains file id + row id, which means that after compaction, a record's row id could change.

**Comment by yinfredyue** [comment]
> We don't have pk.

Does that mean RisingLight does not store pks? I am pretty sure you can have pk when creating tables.

```
pub struct BoundCreateTable {
    pub database_id: DatabaseId,
    pub schema_id: SchemaId,
    pub table_name: String,
    pub columns: Vec<ColumnCatalog>,
    pub ordered_pk_ids: Vec<ColumnId>,
}
```

> Row handler is like a row id, but row handler contains file id + row id, which means that after compaction, a record's row id could change.

So row_handler = file id + row id. Does the row_id equal to a row's index in the entire table?

**Comment by skyzh** [comment]
No. It's the offset in the RowSet.

**Pull request merged**
