### PR TITLE
chore: update toolchain and dependencies

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Do you need any help? I also want to bump the toolchain for `async gen`.

**Comment by caicancai** [comment]
> Do you need any help? I also want to bump the toolchain for `async gen`.

I am trying this part of the work, but I am not very familiar with the rust toolchain ecology, I can close this pr if the big guy is willing to do this part of the work

**Comment by wangrunji0408** [comment]
CI shows the clippy [panicked](https://github.com/risinglightdb/risinglight/actions/runs/7928052433/job/21645540229?pr=830#step:7:701)
Let's try a newer version?

**Comment by caicancai** [comment]
> CI shows the clippy [panicked](https://github.com/risinglightdb/risinglight/actions/runs/7928052433/job/21645540229?pr=830#step:7:701) Let's try a newer version?

Thank you

**Review by wangrunji0408 — APPROVED** [review]
Thank you!

**Comment by caicancai** [comment]
> Do you need any help? I also want to bump the toolchain for `async gen`.

finish

**Pull request merged**
