### PR TITLE
executor: hash join support multi columns as hash key.

### PR DESCRIPTION
**Pull request by xxchan**
closes https://github.com/risinglightdb/risinglight/issues/362

- `PhysicalHashJoin`'s `left/right_column_index` fields are deleted, only `logical` left. 
- `HashJoinExecutor`'s same fields are changed from `index` -> `indexes`. They are computed in `visit_physical_hash_join` now. (Previously in `rewrite_logical_join`)

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
Generally LGTM, better to add some e2e test cases in https://github.com/risinglightdb/risinglight/blob/main/tests/sql/join.slt?

btw, could you provide some examples of plans after this change?

**Comment by xxchan** [comment]
main branch:

image


---

Last version: There's unnecessary Eq in the pulled filter! I should have tested it carefully 😭

image

--- 

Current version:

image

**Comment by xxchan** [comment]
Swapping LHS and RHS of equations works correctly

image

**Review by skyzh — APPROVED** [review]

**Review by st1page — APPROVED** [review]
optimizer part LGTM

**Pull request merged**
