### PR TITLE
feat(storage): support multi-thread execution for table scan

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

part of https://github.com/risinglightdb/risinglight/issues/366

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]
LGTM

**Review by wangrunji0408 — COMMENTED** [review]
We can do this in `ExecutorBuilder` so that all executors will benefit.

**Comment by skyzh** [comment]
> We can do this in `ExecutorBuilder` so that all executors will benefit.

For the more general case, I think we should use optimizer to decide which node to exchange with a `PhysicalExchange` plan node. See https://github.com/risinglightdb/risinglight/pull/367.

**Comment by st1page** [comment]
> We can do this in `ExecutorBuilder` so that all executors will benefit.

https://github.com/risinglightdb/risinglight/pull/367#pullrequestreview-866848198

**Pull request merged**
