### PR TITLE
feat(type): support type-string for timestamp type

### PR DESCRIPTION
**Pull request by caicancai**
I feel like it’s very simple whether timestamp will support it. There may be some problems that I didn’t pay attention to.

### CODE REVIEW

**Comment by caicancai** [comment]
I'm thinking about whether I need to support time type

**Review by wangrunji0408 — APPROVED** [review]
LGTM!

Actually the timestamp type is already supported.

```
> select '2022-01-01 00:00:00'::timestamp;
+---------------------+
| 2022-01-01 00:00:00 |
+---------------------+
in 0.034s
```

What you have done in this PR is the **type-string support** for timestamp type.

```
timestamp '2022-01-01 00:00:00'
```

Thank you for your contribution! Even though it is a small step.

**Comment by wangrunji0408** [comment]
> I'm thinking about whether I need to support time type

Feel free to have a try. It would be more challenging than this one. 😀

**Comment by caicancai** [comment]
> > I'm thinking about whether I need to support time type
> 
> Feel free to have a try. It would be more challenging than this one. 😀

Thanks, I'm going to try it, I want to ask about the writing of the optimizer I may not understand very well, is this a rust-specific way of writing.
```rust
rw!("inner-join-on-right-empty"; "(join inner ?on ?l (empty ?r))"   => "(empty ?l ?r)"),
```

**Pull request merged**
