### PR TITLE
feat: support TPC-H Q9

### PR DESCRIPTION
**Pull request by wangrunji0408**
With subquery support in #756, we are able to challenge more TPC-H queries.
As an example, this PR adds support for TPC-H Q9.

Changes:

- support `like` operator
- support `extract(year from xx)` function
- update `sqlparser-rs` version to 0.30 (for deriving`Ord`)
- add TPC-H Q9 to test

However, the speed for this query is ridiculously slow. (104s vs DuckDB <1s)
We should investigate and optimize it in the future.

### CODE REVIEW

**Review by MingjiHan99 — APPROVED** [review]
LGTM!

**Review by skyzh — APPROVED** [review]
LGTM. Q9 contains a lot of joins, and I guess we need to see if the join order is not optimal.

**Comment by wangrunji0408** [comment]
Any idea about the failing CI? It only said `The operation was canceled.` 🥵

**Comment by skyzh** [comment]
I guess it’s OOM or something…

**Pull request merged**
