### PR TITLE
feat(ci): parallism test

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

close https://github.com/risinglightdb/risinglight/issues/565

### CODE REVIEW

**Review by xxchan — APPROVED** [review]
😍😍😍

**Comment by xxchan** [comment]
Still not fast enough? 🤪

**Comment by skyzh** [comment]
> Still not fast enough? 🤪

Yes. I think it's better to re-introduce the `build.rs`, but in a separate crate. e.g. `risinglight-sqllogictest` crate. Therefore, we can avoid re-building the whole binary if only test cases get changed.

**Comment by xxchan** [comment]
~Why we didn't come up with that earlier?~ 

Oh I missed the discussion 🤪
> How about moving the integration test into a separate crate?

_Originally posted by @Fedomn in https://github.com/risinglightdb/risinglight/issues/472#issuecomment-1043775252_

**Comment by skyzh** [comment]
Apart from separating a `risinglight-sqllogictest` crate, we also added a new in-memory file backend, which speeds up 2x on each disk unit tests :)

**Pull request merged**
