### PR TITLE
feat(executor): improve explain of OrderBy and NLJ

### PR DESCRIPTION
**Pull request by WindowsXp-Beta**
part of https://github.com/risinglightdb/risinglight/issues/410

### CODE REVIEW

**Comment by WindowsXp-Beta** [comment]
Forgot to sign DCO, my bad, trying to fix it.

**Comment by WindowsXp-Beta** [comment]
Didn't find a good way :(

**Review by skyzh — APPROVED** [review]
LGTM, thanks!

In the future, you can refer the issue in the PR, so that people can easily track changes for an issue. I've modified the PR body for you.

**Comment by WindowsXp-Beta** [comment]
> you can refer the issue in the PR

gotcha. Getting familiar with github's workflow.

**Pull request merged**
