### PR TITLE
chore: bump deps version, patch nondeterministic in egg

### PR DESCRIPTION
**Pull request by skyzh**

### CODE REVIEW

**Comment by skyzh** [comment]
It seems that the generated prettier result is not stable across platforms. Something wrong with UTF-8 with estimation?

**Comment by xxchan** [comment]
cc @ice1000

**Review by xxchan — APPROVED** [review]

**Comment by ice1000** [comment]
> It seems that the generated prettier result is not stable across platforms. Something wrong with UTF-8 width estimation?

I am using the standard `s.chars().count()`, is that stable across platforms?

**Review by xxchan — COMMENTED** [review]
It's the order of the exprs that changed


image

**Comment by xxchan** [comment]
It's not related to the prettier, run `make apply_planner_test` on 70acb0e will also cause a diff here 😅
image

**Comment by ice1000** [comment]
Turns out using ordered btreemap was better than this lmao

**Comment by ice1000** [comment]
By the way I have observed a problem with the pretty printing crate. I'll have to fix it. It should inline singleton lists

**Comment by xxchan** [comment]
> Turns out using ordered btreemap was better than this lmao

ordered btreemap will prevent us from finding this thing 🤣

**Comment by wangrunji0408** [comment]
I also noticed this problem before. I believe it's caused by the egg. Because the plan is generated by egg's runner and extracted using our cost function, where identical expressions (e.g. `a AND b`, `b AND a`) should have the same cost.
So any of them could be part of the best plan. But I have no idea why it is not stable across platforms. By the way, we also ran into this problem in deterministic testing of RisingWave. 🤪

**Review by wangrunji0408 — APPROVED** [review]

**Comment by xxchan** [comment]
> But I have no idea why it is not stable across platforms. By the way, we also ran into this problem in deterministic testing of RisingWave

Guess there must be some non-determinism 🤪

**Comment by skyzh** [comment]
Hmm, I'd prefer fixing non-determinism before merging this PR. I'll take a look later.

**Comment by skyzh** [comment]
fixed by patching egg, probably we can submit a PR to upstream to add a `deterministic` feature?

**Comment by xxchan** [comment]
successful！

**Comment by ice1000** [comment]
> fixed by patching egg, probably we can submit a PR to upstream to add a `deterministic` feature?

Wtf how did you fix that?

**Comment by skyzh** [comment]
by replacing hashmap -> index(btree)map

**Comment by ice1000** [comment]
Lmao gotcha

**Comment by mwillsey** [comment]
hi :wave: egg developer here. Very cool work! I'd be interested in fixing any sources of non-determinism. I see [your patch](https://github.com/egraphs-good/egg/compare/main...risinglightdb:egg:skyzh/determinstic), but as far as I can tell it should not matter! We were using a deterministic hash function (fxhash)... shouldn't that be enough?

**Comment by skyzh** [comment]
Yeah, I'm also surprised why it happened. I guess it's because non-deterministic in resizing the hash table, but I didn't look into it... One of RisingLight developer developed https://github.com/madsim-rs/madsim, which can detect non-determinism in Rust.

**Comment by skyzh** [comment]
I also guess it's a platform-dependent thing because it always yield the same value in a single platform...

**Comment by mwillsey** [comment]
Ok, I have added this as the `deterministic` feature: https://github.com/egraphs-good/egg/commit/967a3db0c059fc17bbb2da8cc4d4c59eb5f093e0

**Comment by mwillsey** [comment]
My guess is that somewhere in your code a hash value is being computed from a pointer (as a value), which would explain the non-det even with a deterministic hash function and the non-det across platforms (different allocators). Either way, indexmap (as used in the above patch) should fix it!

**Pull request merged**
