### PR TITLE
feat(executor): support group by expression

### PR DESCRIPTION
**Pull request by Fedomn**
try to close https://github.com/risinglightdb/risinglight/issues/526

Signed-off-by: Fedomn <fedomn.ma@gmail.com>

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM, thanks a lot for this big feature!

**Review by st1page — APPROVED** [review]
LGTM, thanks for your contribution!
BTW, I think we should refactor the `Bound::Expr` some day, because it seems to cause our some trouble...

**Comment by skyzh** [comment]
Yes, we are implementing too many things on `Bound::Expr`... Maybe we can implement some visitors for expr :)

**Comment by xxchan** [comment]
The header is incorrect
```sql
> SELECT c0+1, c0+1+count(*) FROM t1 GROUP BY c0+1; 
+----+----------+
| c0 | ?column? |
+----+----------+
| 4  | 5        |
| 2  | 3        |
+----+----------+
in 0.004s
```


This reports error
```sql 
> SELECT c0+2 FROM t1 GROUP BY c0+1; 
logical plan error: (Column #ColumnRefId { database_id: 0, schema_id: 0, table_id: 2, column_id: 0 } + 2) must appear in the GROUP BY clause or be used in an aggregate function
```
But this panics
```sql
> SELECT c0+2+count(*) FROM t1 GROUP BY c0+1; 
thread 'tokio-runtime-worker' panicked at 'Column #ColumnRefId { database_id: 0, schema_id: 0, table_id: 2, column_id: 0 } should not be evaluated in `eval_array`', src/executor/evaluator.rs:55:18

**Comment by xxchan** [comment]
```sql
> select c0*1 from t1 group by c0*1
+----+
| c0 |
+----+
| 3  |
| 1  |
+----+
in 0.004s
> select c0*0 from t1 group by c0*0
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/optimizer/plan_nodes/logical_projection.rs:66:25
```

**Comment by Fedomn** [comment]
Thanks for your input!

> But this panics
> 
> ```sql
> > SELECT c0+2+count(*) FROM t1 GROUP BY c0+1; 
> thread 'tokio-runtime-worker' panicked at 'Column #ColumnRefId { database_id: 0, schema_id: 0, table_id: 2, column_id: 0 } should not be evaluated in `eval_array`', src/executor/evaluator.rs:55:18
> ```

... it seems should report logical plan error that same behavior as postgres



> ```sql
> > select c0*1 from t1 group by c0*1
> +----+
> | c0 |
> +----+
> | 3  |
> | 1  |
> +----+
> in 0.004s
> > select c0*0 from t1 group by c0*0
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/optimizer/plan_nodes/logical_projection.rs:66:25
> ```

... it seems to be a bug. 
Because after `ArithExprSimplificationRule` rewrite_expr, `c0*0` will rewrite to `Constant(Int32(0))` and the LogicalProjection's child_schema will be empty, however `project_expressions` already replaced to `InputRef #0`, so when get projection schema caused panic.
currently, I'm not sure how to resolve this, maybe just return `"?column?"` when child schema is empty?

**Pull request merged**
