### PR TITLE
stroage: Add O_DIRECT support

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR adds a basic `O_DIRECT` for column read.

Part of https://github.com/risinglightdb/risinglight/issues/378

## TODO

- [ ] Align with 4K block to avoid `Invalid argument` error.

### CODE REVIEW

**Comment by Xuanwo** [comment]
Clippy will complain about enum postfix (first known...)

```rust
error: all variants have the same postfix: `Read`
  --> src/storage/secondary/options.rs:10:1
   |
10 | / pub enum IOBackend {
11 | |     /// Use Linux's `pread` API to read from the files that opened via `O_DIRECT`.
12 | |     DirectPositionedRead,
13 | |     /// Use Linux's `pread` API to read from the files.
...  |
16 | |     NormalRead,
17 | | }
   | |_^
   |
   = note: `-D clippy::enum-variant-names` implied by `-D warnings`
   = help: remove the postfixes and use full paths to the variants instead of glob imports
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names
```

ping @skyzh for advice

**Comment by Xuanwo** [comment]
> What about renaming to `DirectPositioned`, `Positioned` and `Normal`?

How about more clear names like: `SeekRead`, `Pread`, `DirectPread`

**Comment by skyzh** [comment]
Sounds good!

**Comment by xxchan** [comment]
Any update? 😊

**Comment by Xuanwo** [comment]
> Any update? blush

No updates so far. I expect to come back in next week.

**Comment by Xuanwo** [comment]
I have lost interest in this issue. Feel free for taking this over.

**Pull request closed without merging**
