### PR TITLE
fix(type): add NULL type and fix type analysis

### PR DESCRIPTION
**Pull request by wangrunji0408**
This PR adds a NULL variant to the `DataTypeKind` enum, as the type of NULL value. And fixes the remaining failed tests in type analysis.

### CODE REVIEW

**Comment by skyzh** [comment]
In general NULL should be part of the type itself (e.g., int null, varchar null) instead of a separate data type kind? Though I'm okay with this change.

**Comment by wangrunji0408** [comment]
> In general NULL should be part of the type itself (e.g., int null, varchar null) instead of a separate data type kind?

Do you mean "nullable"? (e.g. int nullable, varchar not nullable)

The null type in this PR means an "unknown" type for a single NULL value. Previously we represent this by a `None` in `Option<DataType>`, and now it will be `DataType { kind: Null, nullable: true }`.

**Comment by skyzh** [comment]
Oh that seems fine!

**Review by skyzh — APPROVED** [review]
Good work!

**Pull request merged**
