### PR TITLE
feat(optimizer): support (filter_agg_rule + having clause)

### PR DESCRIPTION
**Pull request by lokax**
**Support having clause and alias**
```sql
select count(x) as a, y as b from test group by b having a > 1

select 42 having 42 > 18;
```
**Forbid to generate:**
```sql
select count(x) from test group by count(x)
```

**Support push the filter down below the agg**
**Before:**
```text
> explain select count(x), y + 1 from test group by y + 1 having count(x) > 1 and y + 1 = 2;
PhysicalProjection:
    InputRef #1
    InputRef #0
  PhysicalFilter: expr And(Gt(InputRef #1, Int32(1) (const)), Eq(InputRef #0, Int32(2) (const)))
    PhysicalHashAgg:
        (InputRef #1 + 1)
        count(InputRef #0) -> INT
      PhysicalTableScan:
          table #13,
          columns [0, 1],
          with_row_handler: false,
          is_sorted: false,
          expr: None
``` 
**After:**
```text
> explain select count(x), y + 1 from test group by y + 1 having count(x) > 1 and y + 1 = 2;
PhysicalProjection:
    InputRef #1
    InputRef #0
  PhysicalFilter: expr Gt(InputRef #1, Int32(1) (const))
    PhysicalHashAgg:
        (InputRef #1 + 1)
        count(InputRef #0) -> INT
      PhysicalTableScan:
          table #13,
          columns [0, 1],
          with_row_handler: false,
          is_sorted: false,
          expr: Eq(Plus(InputRef #1, Int32(1) (const)), Int32(2) (const))
```

### CODE REVIEW

**Review by xxchan — COMMENTED** [review]
I think filter_agg_rule and having clause can be splited into 2 atomic PRs. Or do you have some special reasons to implement them together?

**Comment by lokax** [comment]
> I think filter_agg_rule and having clause can be splited into 2 atomic PRs. Or do you have some special reasons to implement them together?
No😑 
Just for testing.
Because the having clause can create a filter above the agg operator.

**Comment by lokax** [comment]
> I think filter_agg_rule and having clause can be splited into 2 atomic PRs. Or do you have some special reasons to implement them together?

No😑
Just for testing.
Because the having clause can create a filter above the agg operator.

**Comment by xxchan** [comment]
Oh yes it makes sense since we don't have subquery yet 😇

**Review by xxchan — COMMENTED** [review]
The rule LGTM. But I haven't looked at the implementation of `having` yet, and it seems non-trivial. Could you please create a new PR for `having` and briefly explain the ideas of the implementation? 😊

**Pull request closed without merging**
